# Generated by Django 4.2.5 on 2023-10-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('uuid', models.CharField(max_length=20)),
                ('click_count', models.IntegerField(default=0)),
                ('last_clicked', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
