# Generated by Django 4.2.5 on 2023-10-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_alter_urls_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='last_clicked',
            field=models.DateTimeField(null=True),
        ),
    ]
